In [68]:
import torch

# Define the tensor
tensor = torch.tensor([10, 5, 10, 15, 20])

# Get the number of elements in the tensor
n = tensor.size(0)

# Create an empty matrix to store the results
output_matrix = torch.zeros((n, n), dtype=torch.long)

# Compare each element with every other element
for i in range(n):
    # Extract the current element to compare against
    current_element = tensor[i]
    
    # Fill the row of the matrix with the correct comparison values
    output_matrix[i] = torch.where(tensor < current_element, 
                                   torch.tensor(0, dtype=torch.long),
                                   torch.where(tensor == current_element, 
                                               torch.tensor(1, dtype=torch.long),
                                               torch.tensor(2, dtype=torch.long)))

print("Original tensor:", tensor)
print("Output matrix:\n", output_matrix)


Original tensor: tensor([10,  5, 10, 15, 20])
Output matrix:
 tensor([[1, 0, 1, 2, 2],
        [2, 1, 2, 2, 2],
        [1, 0, 1, 2, 2],
        [0, 0, 0, 1, 2],
        [0, 0, 0, 0, 1]])


In [70]:
output_matrix.flatten()

torch.Size([25])

In [66]:
tensor @ tensor.T

tensor([[100,  50, 100, 150, 200],
        [ 50,  25,  50,  75, 100],
        [100,  50, 100, 150, 200],
        [150,  75, 150, 225, 300],
        [200, 100, 200, 300, 400]])

In [4]:
tensor @ tensor.T

tensor(850)

In [54]:
import torch

# Define the embedding matrix (5 x 128)
embedding_matrix = torch.randn(5, 128)

# Get the number of rows in the embedding matrix
num_rows = embedding_matrix.size(0)

# Initialize a list to store pairwise concatenated embeddings
pairwise_embeddings = []

# Generate pairwise concatenated embeddings
for i in range(num_rows):
    for j in range(num_rows):  # Ensure pairs are unique
        # Concatenate embeddings from row i and row j
        concatenated = torch.cat((embedding_matrix[i], embedding_matrix[j]), dim=0)
        pairwise_embeddings.append(concatenated)

# Convert list of tensors to a single tensor
pairwise_embeddings_matrix = torch.stack(pairwise_embeddings)

# Print shapes to verify
print("Embedding matrix shape:", embedding_matrix.shape)
print("Pairwise embeddings matrix shape:", pairwise_embeddings_matrix.shape)


Embedding matrix shape: torch.Size([5, 128])
Pairwise embeddings matrix shape: torch.Size([25, 256])


In [55]:
embedding_matrix

tensor([[-2.0134e+00,  1.4611e+00, -7.8293e-01,  6.9609e-01,  4.8444e-01,
          1.1393e+00, -8.5221e-01, -1.6264e+00, -6.7714e-01, -2.4328e+00,
          4.7671e-01, -1.1517e+00, -1.4596e+00, -5.0996e-01,  2.2365e-01,
         -6.1374e-02, -1.0140e+00,  6.1356e-01, -8.4270e-02, -1.0102e+00,
          4.4242e-01, -1.9984e+00,  1.2542e+00,  7.1929e-01, -5.6129e-01,
          3.1783e-01,  4.9972e-01,  1.7425e-01,  4.8911e-01, -5.4969e-01,
         -5.4936e-01,  5.1140e-01, -3.9898e-01, -1.0776e+00,  1.4730e-02,
         -9.1950e-01,  7.3325e-01,  1.1437e+00, -1.2801e-01,  4.3065e-01,
         -1.0361e+00, -1.8642e+00, -7.8827e-01, -1.5666e+00,  7.4162e-01,
          1.1092e+00,  3.1726e-01, -1.1296e-01, -1.2023e+00,  1.6326e+00,
          7.2594e-02, -1.0079e+00, -3.3135e-01,  2.0921e-01, -6.1901e-01,
          6.4580e-01,  1.9848e+00, -7.3644e-01, -6.6276e-01, -8.6202e-01,
          1.0710e+00, -5.1565e-02,  1.4550e+00,  1.1163e+00, -1.1616e-01,
         -2.9639e-01, -7.6344e-01, -8.

In [56]:
embedding_matrix[0].shape

torch.Size([128])

In [62]:
pairwise_embeddings_matrix[4][:128] == embedding_matrix[0]

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [53]:
pairwise_embeddings_matrix[0][128:] == embedding_matrix[0]

RuntimeError: The size of tensor a (472) must match the size of tensor b (300) at non-singleton dimension 0

In [52]:
pairwise_embeddings_matrix.shape

torch.Size([16384, 600])

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the pairwise embeddings matrix (25 x 256)
pairwise_embeddings = torch.randn(25, 256)

# Define the label matrix (25,) with class indices for each pairwise embedding
labels = torch.randint(0, 3, (25,))  # Example labels for 3 classes

# Define the linear layer (256 -> 3)
linear_layer = nn.Linear(256, 3)

# Apply the linear transformation
logits = linear_layer(pairwise_embeddings)

# Define the cross-entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(logits, labels)

print("Logits:\n", logits)
print("Labels:\n", labels)
print("Loss:\n", loss.item())


Logits:
 tensor([[ 0.2220, -0.2920, -0.3507],
        [-0.8946,  0.2897,  0.2469],
        [-0.2287,  0.1828,  0.5999],
        [ 0.4986, -0.3846, -1.1352],
        [-0.1706, -0.5710,  0.2185],
        [-0.5212,  0.3408,  0.4124],
        [ 0.5458, -0.6454,  0.0977],
        [-0.6668, -0.4272, -0.6196],
        [-0.1009, -0.0832,  0.0188],
        [ 0.7093, -0.3336, -0.1101],
        [-0.3309,  0.3851, -0.8583],
        [ 0.6945, -0.6904, -0.3053],
        [-0.1590,  0.0448, -0.0356],
        [ 0.2188,  0.6905,  0.0321],
        [-0.1988, -0.7908,  0.5962],
        [-0.1032,  0.0029, -0.1704],
        [ 0.1417, -0.0117,  0.5900],
        [-0.8979, -0.6044, -0.8794],
        [ 0.8302, -0.0522,  0.3876],
        [ 0.3450, -0.7952,  0.3969],
        [-0.6418, -0.2482,  0.1200],
        [ 0.6546, -0.6348, -0.7047],
        [ 0.1877,  0.1375, -1.6608],
        [ 0.2701, -0.2194, -0.2379],
        [-0.0050, -0.0116,  0.2958]], grad_fn=<AddmmBackward0>)
Labels:
 tensor([2, 1, 0, 1, 0, 1, 2, 0

In [22]:
from chemprop.models import MoleculeModel,mpn

In [23]:
from chemprop.args import TrainArgs

In [24]:
arguments = [
    '--data_path', 'Utils/dataset_nmrshiftdb2_smiles_modified_1204.pkl',
    '--dataset_type', 'kmgcl',
    '--smiles_columns','smiles'
    ]

pass_args=TrainArgs().parse_args(arguments)

['smiles']
1


In [25]:
graph_model = mpn.MPN(pass_args).to("cpu")

In [40]:
labels = torch.randint(0, 3, (25,))  

In [41]:
labels

tensor([0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 0, 1,
        2])

In [42]:
pairwise_embeddings = torch.randn(25, 256)

In [44]:
pairwise_embeddings.shape

torch.Size([25, 256])

In [45]:
linear_layer = nn.Linear(256, 3)

# Apply the linear transformation
logits = linear_layer(pairwise_embeddings)

In [47]:
logits.shape

torch.Size([25, 3])

In [51]:
import torch

# Define the embedding matrix (5 x 128)
embedding_matrix = torch.randn(128, 300)

# Get the number of rows in the embedding matrix
num_rows = embedding_matrix.size(0)

# Initialize a list to store pairwise concatenated embeddings
pairwise_embeddings = []

# Generate pairwise concatenated embeddings
for i in range(num_rows):
    for j in range(num_rows):  # Ensure pairs are unique
        # Concatenate embeddings from row i and row j
        concatenated = torch.cat((embedding_matrix[i], embedding_matrix[j]), dim=0)
        pairwise_embeddings.append(concatenated)

# Convert list of tensors to a single tensor
pairwise_embeddings_matrix = torch.stack(pairwise_embeddings)

# Print shapes to verify
print("Embedding matrix shape:", embedding_matrix.shape)
print("Pairwise embeddings matrix shape:", pairwise_embeddings_matrix.shape)


Embedding matrix shape: torch.Size([128, 300])
Pairwise embeddings matrix shape: torch.Size([16384, 600])
